### ISSUE TITLE
Raft Consensus

### ISSUE THREAD

**Issue by thedodd** [hadron-project/hadron#5]
In GitLab by @doddzilla on May 27, 2019, 22:37

### todo
- [x] refactor `db` code. Everything goes through Raft now.
- [x] finish updates to the guide & book! This will help streamline development.
- [x] pin down proto code for what will be used as client request data. Proto code will just map to a src/db/raft module's type which uses binary encoding (zero-allocation) for ser/de. Those types will map back out to the appropriate protobuf response types as needed (for consumers and such).
- [x] stub out impl `actix_raft::RaftStorage` for the db actor.
  - [x] finish business logic impl.
- [x] stub out impl `actix_raft::RaftNetwork` for the `Network` actor.
  - [x] update outbound frame pattern in network actor & peer connection actors.
    - Network actor should not be generic, it should have handlers for each of the specific outbound frame types, shared routing_table look-up patterns &c.
    - Child connection actors should have a handler for taking a request object, should give it a meta object with request ID, serialize it and send it over the socket. In the future, we will introduce a new frame variant for oneshots.
  - [x] finish business logic impl.
- [x] impl handler of `actix_raft::RaftMetrics` for `App` actor.
- [x] communication is not being restored properly between peers after a node goes down. Need to revisit heartbeat/reconnect/disconnect protocol to ensure proper communication is re-established during disconnect conditions. That is why nodes are not re-syncing.
