### ISSUE TITLE
Require id & source as input from clients

### ISSUE THREAD

**Issue by thedodd** [hadron-project/hadron#94]
Per the CloudEvents spec, `id` and `source` are supposed to be provided by producers.

As it turns out, this greatly simplifies transactional processing models, as there is no disconnect between the Hadron CloudEvents id+source identity vs the ID established by a producer in the host application.

The current model is using the partition's monotonically increasing `u64` offset as the `id` and is generating a `source` field based on the cluster_name + stream + partition.

### todo
- [x] remove the "cluster_name" field from CRD & config items.
- [x] update proto model to expect `id` & `source` fields to be passed in.
    - [x] update client code to have a `new` constructor which takes both fields, and another which will generate a uuid4 for the `id` and takes on the source.
- [x] ~~maybe: add new extension fields to the model for `hadron_offset` & `hadron_partition`. I think this may actually be unneeded as it is really only used for Hadron bookkeeping.~~ Not needed. This data is really only useful for monitoring / metrics.
- [x] minimal updates needed in storage layer, as the offset is only used for sequential storage/ordering. No manipulation of the event will be needed.
- [x] update client code & cli as needed.

**Comment by thedodd** [comment]
Closed by https://github.com/hadron-project/hadron/pull/96
